title: Gino Pack's Blog
description: Let's Learn Together
author: Gino Pack

baseurl: "/blog" # the subpath of your site, e.g. /blog — leave empty if using a *.github.io repo
url: "https://ginopack.github.io" # the base hostname & protocol, e.g. https://username.github.io


# Build settings
theme: minima #change theme eventually

minima:
  social_links:
    twitter: ginopack
    linkedin: gino-pack
    github: ginopack
    
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
