title: Gino Pack's Blog
description: Let's Learn Together
author: Gino Pack
email: gino@ginopack.com

baseurl: "/blog" # the subpath of your site, e.g. /blog — leave empty if using a *.github.io repo
url: "https://ginopack.github.io" # the base hostname & protocol, e.g. https://username.github.io


# Build settings
theme: minima #change theme eventually

# Controls which pages appear in the header nav, and in what order
header_pages:
  - about.md
  - posts.md
  - categories.md
  - speaking-engagements.md
    
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
